// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADuIXcevjs2kdBixVuK0sBk27LGP8B-p0',
    appId: '1:913202030906:web:d863dc47446f1f2c9b8803',
    messagingSenderId: '913202030906',
    projectId: 'portfolio-f4d80',
    authDomain: 'portfolio-f4d80.firebaseapp.com',
    storageBucket: 'portfolio-f4d80.appspot.com',
    measurementId: 'G-830VGWKM5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5OtLREKKzkybuLLUhxE5-59cibYBAbUI',
    appId: '1:913202030906:android:8f97d0e54f2853759b8803',
    messagingSenderId: '913202030906',
    projectId: 'portfolio-f4d80',
    storageBucket: 'portfolio-f4d80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1IhImtkcD9_e_tyclx8eWqSigfc86x2g',
    appId: '1:913202030906:ios:f63b01355b757c939b8803',
    messagingSenderId: '913202030906',
    projectId: 'portfolio-f4d80',
    storageBucket: 'portfolio-f4d80.appspot.com',
    iosBundleId: 'com.example.portfolioWebsiteForLinkedin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1IhImtkcD9_e_tyclx8eWqSigfc86x2g',
    appId: '1:913202030906:ios:b9e490d77d06df069b8803',
    messagingSenderId: '913202030906',
    projectId: 'portfolio-f4d80',
    storageBucket: 'portfolio-f4d80.appspot.com',
    iosBundleId: 'com.example.portfolioWebsiteForLinkedin.RunnerTests',
  );
}
